### PR TITLE
Update preload

### PR DESCRIPTION
**Pull request by Nep-Timeline**
Maybe can solve the problem of character image loss

### CODE REVIEW

**Comment by Ada18980** [comment]
I disable preload usually when I develop assets, because I end up going back and changing stuff to make it more compatible.

Texture packing takes a while. But it definitely helps with performance.

**Comment by Nep-Timeline** [comment]
> I disable preload usually when I develop assets, because I end up going back and changing stuff to make it more compatible.
> 
> Texture packing takes a while. But it definitely helps with performance.

OK, thanks

**Comment by Ada18980** [comment]
However adding a dressplayer call may be the right idea to refresh the model.

**Comment by Nep-Timeline** [comment]
> However adding a dressplayer call may be the right idea to refresh the model.

if dressplayer is not called on the Intro or Menu page, the character will have no head ;(

**Pull request closed without merging**
