### PR TITLE
[Please merge this PR before other translation files] Fix auto formatting translation some issue

### PR DESCRIPTION
**Pull request by Nacosia**
I apologize for not being thorough enough and not considering that there might still be some minor "surprises" under certain circumstances. Therefore, before merging other translation files, I would like to ask you to merge this PR first. This is because once the translation files are merged, Github Action will start running, which could potentially cause some minor issues. Of course, these issues are not serious and will only affect a very small portion of the translation entries.

#### 1. format-translation-script.py
- Fixed the issue where annotations could be accidentally treated as translations.
- Repeated translations now will also be considered untranslated

#### 2. Github Action (format-translation.yml)
Remove an undeserved trigger condition

#### 3. About translation and revision

These translation formats have some surprising effects: (

When the coincidence in the original text is the translation of a word, it may lead to the mistranslation of the coincidental word into another word after formatting. This may lead to some chain reactions.

As follows, the translation of "Restart required!" "In the original text is also coincidentally" need to restart! " After formatting, the first "Restart required!" "In the original text is correctly translated into" need to restart! " , but the second original "needs to be restarted!"! "Will be incorrectly translated as" Domit "in the translation (this is a connected text)

There is no good solution to this problem, because it is impossible to absolutely judge which is the original text and which is the translation. Unless the matching logic is reconstructed to bind KEY instead of text when translating, it can also solve the translation problem of the same text for items with different ids. I don't think it's worth doing so in a short time. It's easy to affect the existing stability if the change is too big.

Fortunately, there are not many cases of this problem. I manually fixed the potentially problematic text that was found, and this is the best workaround for now.

csv file
```
RestartNeededEN,"Restart required!"
RestartNeededCN,"需要重启！"
```

File before formatting
```
Restart required!
需要重启！
Domit
支配者
```

File after formatting
```
Restart required!
需要重启！
需要重启！
Domit
### 재시작 필요！
### Restart please!
### ¡Reinicio!
### Rechargement requis!
```

### CODE REVIEW

**Comment by Ada18980** [comment]
<3

**Comment by Ada18980** [comment]
So I have a question @Nacosia,
`###` appear to be comments.
Do comments factor into the fact that even lines are supposed to be original and odd lines are supposed to be translations?

Because this is causing problems with a lot of translations due to newlines appearing in the translation files

I am planning to trim empty lines to hopefully resolve this.

**Comment by Nacosia** [comment]
@Ada18980 
In fact comment lines will be filtered and the translation read without comment lines within the list of variables.  Instead of judging the original text or translation by odd or even lines, the next line after the original text is read will be considered as a translation. (Here I refer to the parsing method of TranslationParseTXT function in Translation.ts).

If the next line of the original text in the translation file is a blank line, this will be considered untranslated, so theoretically the line breaks won't affect the logic.

Can you give me some examples regarding this issue? I will check what the problem is as soon as possible.  :D



> A known bug is that when the translation is the same as one of the original texts, it will be possible to read the translation incorrectly, which can't be avoided without an ID. The main problem is in the text with ID “RestartNeeded<lang>”, because there is always a translator to translate it, and in fact it should not be translated.
I plan to deal with it by adding a filter.

*(The above partially uses a translator, so there may be inaccuracies)*

**Comment by Nacosia** [comment]
I don't know if this is the problem you are referring to:

I noticed that in the commit(ff67ee8f) of the recent translation file, where the space at the end of 'original text' seems to have been removed, but in the source text csv there is a space in the original text, which would prevent the formatter from recognizing that this corresponds, since I didn't remove the spaces at both ends for comparison to avoid some surprises.

For example
In csv.
`` 
key1, source_value1:[space]
key2, source_value2:[space]
```
In the translation, since the spaces in the original were removed
```
source_value1:[no spaces]
source_value1:[no spaces

source_value1:[no spaces]
translate
``

Here
source_value1:[spaces] is not the same as source_value1:[no spaces], so the formatter will not be able to find the translation, and this is also true in the function “TranslationParseTXT”.

If necessary, I'll modify it so that it ignores spaces at both ends.

== Edited ==

PR https://github.com/Ada18980/KinkiestDungeon/pull/159

**Comment by Nacosia** [comment]
> Do comments factor into the fact that even lines are supposed to be original and odd lines are supposed to be translations?

Well... I looked at more of the source code. I think I may have misunderstood the meaning of the sentence due to translation software issues. Do you mean that it is mandatory in programming that the original text must be on odd lines and the translation on even lines?

But I tried some tests and there were no surprises when the original text was on even numbered lines 🤔

**Comment by Ada18980** [comment]
It is mandatory, but I edited the code now so it skips whitespace in
addition to comments

**Pull request merged**
